version = 0.1
[default.deploy.parameters]
stack_name = "multi-service-sam"
resolve_s3 = true
s3_prefix = "multi-service-sam"
region = "us-east-2"
profile = "assets-planet"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
