AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Product Service

  Sample SAM Template for product service

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs18.x
    Layers:
      - !Ref Utils
    Architectures:
      - x86_64
Resources:
  Utils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      ContentUri: ../../utils-layer

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: routes/
      Handler: app.lambdaHandler
      Events:
        GetProduct:
          Type: Api
          Properties:
            Path: /product
            Method: get

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: routes/
      Handler: app.lambdaHandler
      Events:
        CreateProduct:
          Type: Api
          Properties:
            Path: /product
            Method: post

Outputs:
  ProductApi:
    Description: "API Gateway endpoint URL for Prod stage for Product function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GetProductFunction:
    Description: "Get Product Lambda Function ARN"
    Value: !GetAtt GetProductFunction.Arn
  GetProductFunctionIamRole:
    Description: "Implicit IAM Role created for Get Product function"
    Value: !GetAtt GetProductFunctionRole.Arn
